### ISSUE TITLE
Deployment Error for greetings-python

### ISSUE THREAD

**Issue by chowyvincent** [cloud-ark/firstmile#21]
Mac OS Version 10.12.6
Docker Version 18.03.0-ce

(firstmile) Vincents-MacBook-Pro:firstmile chow_vincent$ tail -200 cld.log
03/30/2018 05:02:54 PM Found 'auths' section
03/30/2018 05:02:54 PM Auth data for {0} is absent. Client might be using a credentials store instead.
03/30/2018 05:02:54 PM Found 'credsStore' section
03/30/2018 05:02:54 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
03/30/2018 05:02:54 PM Found file at path: /Users/chow_vincent/.docker/config.json
03/30/2018 05:02:54 PM Found 'auths' section
03/30/2018 05:02:54 PM Auth data for {0} is absent. Client might be using a credentials store instead.
03/30/2018 05:02:54 PM Found 'credsStore' section
03/30/2018 05:02:54 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
03/30/2018 05:02:54 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
03/30/2018 05:02:54 PM <Local deployer called for service mysql>: deploy() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/deployer/local_deployer.py:181
03/30/2018 05:02:54 PM Deploying mysql container
03/30/2018 05:02:54 PM Environment string -e "MYSQL_ROOT_PASSWORD=testpass123!#$" 
03/30/2018 05:02:54 PM Environment string -e "MYSQL_ROOT_PASSWORD=testpass123!#$" -e "MYSQL_PASSWORD=testpass123!#$" 
03/30/2018 05:02:54 PM Environment string -e "MYSQL_ROOT_PASSWORD=testpass123!#$" -e "MYSQL_PASSWORD=testpass123!#$" -e "MYSQL_USER=testuser" 
03/30/2018 05:02:54 PM Environment string -e "MYSQL_ROOT_PASSWORD=testpass123!#$" -e "MYSQL_PASSWORD=testpass123!#$" -e "MYSQL_USER=testuser" -e "MYSQL_DATABASE=testdb" 
03/30/2018 05:02:54 PM Docker run cmd:docker run -e "MYSQL_ROOT_PASSWORD=testpass123!#$" -e "MYSQL_PASSWORD=testpass123!#$" -e "MYSQL_USER=testuser" -e "MYSQL_DATABASE=testdb"  -i -d --publish-all=true mysql:5.5
03/30/2018 05:02:55 PM <[Errno 2] No such file or directory: '/Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/service_handler/mysql/docker_host.txt'>: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
03/30/2018 05:02:55 PM <[Errno 2] No such file or directory: '/Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/service_handler/mysql/docker_host.txt'>: start_thread() cld.py:44
03/30/2018 05:03:02 PM <Executing GET for all apps>: get() cld.py:246
03/30/2018 05:03:30 PM <Executing GET for dep id:2>: get() cld.py:351
03/30/2018 05:03:33 PM <Executing GET for dep id:1>: get() cld.py:351
03/30/2018 05:04:29 PM <Executing GET for all services>: get() cld.py:115
03/30/2018 05:05:42 PM <Received POST request.>: post() cld.py:490
03/30/2018 05:05:42 PM <Untarring received app tar file /Users/chow_vincent/.cld/data/deployments/hello-world/2018-03-30-17-05-42/hello-world.tar>: _untar_the_app() cld.py:414
03/30/2018 05:05:42 PM <App id:2>: post() cld.py:490
03/30/2018 05:05:42 PM <Location header:/deployments/2>: post() cld.py:490
03/30/2018 05:05:42 PM <Starting build/deploy for hello-world>: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
03/30/2018 05:05:42 PM <Response:<Response 3 bytes [201 CREATED]>>: post() cld.py:490
03/30/2018 05:05:46 PM <Executing GET for all apps>: get() cld.py:246
03/30/2018 05:05:47 PM <Local generator called for app hello-world>: generate() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/generator/local_generator.py:108
03/30/2018 05:05:47 PM <App dir: /Users/chow_vincent/.cld/data/deployments/hello-world/2018-03-30-17-05-42>: _generate_for_python_app() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/generator/local_generator.py:33
03/30/2018 05:05:47 PM <Dockerfile dir:/Users/chow_vincent/.cld/data/deployments/hello-world/2018-03-30-17-05-42/hello-world>: _generate_for_python_app() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/generator/local_generator.py:33
03/30/2018 05:05:47 PM <Executing build step>: build() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/builder.py:19
03/30/2018 05:05:47 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
03/30/2018 05:05:47 PM Found file at path: /Users/chow_vincent/.docker/config.json
03/30/2018 05:05:47 PM Found 'auths' section
03/30/2018 05:05:47 PM Auth data for {0} is absent. Client might be using a credentials store instead.
03/30/2018 05:05:47 PM Found 'credsStore' section
03/30/2018 05:05:47 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
03/30/2018 05:05:47 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
03/30/2018 05:05:47 PM <Local builder called for app hello-world>: build() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/local_builder.py:106
03/30/2018 05:05:47 PM <Container name that will be used in building:hello-world-2018-03-30-17-05-42>: _build_app_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/local_builder.py:51
03/30/2018 05:05:47 PM <Docker build cmd:docker build -t hello-world-2018-03-30-17-05-42 -f /Users/chow_vincent/.cld/data/deployments/hello-world/2018-03-30-17-05-42/hello-world/Dockerfile /Users/chow_vincent/.cld/data/deployments/hello-world/2018-03-30-17-05-42/hello-world>: build_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:81
03/30/2018 05:05:50 PM <Executing GET for all apps>: get() cld.py:246
03/30/2018 05:06:03 PM <Executing GET for all apps>: get() cld.py:246
03/30/2018 05:06:13 PM <Executing GET for dep id:1>: get() cld.py:351
03/30/2018 05:06:16 PM <Executing GET for dep id:2>: get() cld.py:351
03/30/2018 05:08:02 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
03/30/2018 05:08:02 PM Found file at path: /Users/chow_vincent/.docker/config.json
03/30/2018 05:08:02 PM Found 'auths' section
03/30/2018 05:08:02 PM Auth data for {0} is absent. Client might be using a credentials store instead.
03/30/2018 05:08:02 PM Found 'credsStore' section
03/30/2018 05:08:02 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
03/30/2018 05:08:02 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
03/30/2018 05:08:02 PM <Local deployer called for app hello-world>: deploy() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/deployer/local_deployer.py:181
03/30/2018 05:08:02 PM <App URL: localhost:32770>: _deploy_app_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/deployer/local_deployer.py:102
03/30/2018 05:08:02 PM <Deleting app tar file>: delete_tar_file() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/utils.py:451
03/30/2018 05:08:02 PM <Deployment result:localhost:32770>: deploy() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/deployer/deployer.py:18
03/30/2018 05:08:02 PM <Result:localhost:32770>: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
03/30/2018 05:09:13 PM <Executing GET for dep id:2>: get() cld.py:351
04/01/2018 01:11:21 PM <Starting LME server>: <module>() cld.py:1
04/01/2018 01:11:37 PM <Executing GET for dep id:1>: get() cld.py:351
04/01/2018 01:11:55 PM <Executing DELETE for dep id:1>: delete() cld.py:327
04/01/2018 01:11:55 PM <App version:2018-03-30-17-02-54>: get_app_and_service_info() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/utils.py:315
04/01/2018 01:11:55 PM <App name:greetings-python>: get_app_and_service_info() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/utils.py:315
04/01/2018 01:11:55 PM <Starting build/deploy for >: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
04/01/2018 01:11:55 PM <Manager -- delete>: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
04/01/2018 01:11:55 PM <Local generator called for delete for app:greetings-python>: generate_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/generator/local_generator.py:96
04/01/2018 01:11:55 PM <Local generator called for delete for service:mysql-greetings-python>: generate_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/generator/local_generator.py:96
04/01/2018 01:11:55 PM <Executing build step for delete>: build_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/builder.py:30
04/01/2018 01:11:55 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
04/01/2018 01:11:55 PM Found file at path: /Users/chow_vincent/.docker/config.json
04/01/2018 01:11:55 PM Found 'auths' section
04/01/2018 01:11:55 PM Auth data for {0} is absent. Client might be using a credentials store instead.
04/01/2018 01:11:55 PM Found 'credsStore' section
04/01/2018 01:11:55 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:11:55 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:11:55 PM <Local builder called for delete of app:greetings-python>: build_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/local_builder.py:65
04/01/2018 01:11:55 PM <Local builder called for delete of service:mysql-greetings-python>: build_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/local_builder.py:65
04/01/2018 01:11:55 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
04/01/2018 01:11:55 PM Found file at path: /Users/chow_vincent/.docker/config.json
04/01/2018 01:11:55 PM Found 'auths' section
04/01/2018 01:11:55 PM Auth data for {0} is absent. Client might be using a credentials store instead.
04/01/2018 01:11:55 PM Found 'credsStore' section
04/01/2018 01:11:55 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:11:55 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:11:55 PM <Local deployer for called to delete app:greetings-python>: deploy_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/deployer/local_deployer.py:139
04/01/2018 01:11:55 PM <Stopping container greetings-python-2018-03-30-17-02-54. Reason: Stopping app cont greetings-python-2018-03-30-17-02-54>: stop_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:50
04/01/2018 01:11:55 PM <Removing container greetings-python-2018-03-30-17-02-54. Reason: Removing app cont greetings-python-2018-03-30-17-02-54>: remove_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:58
04/01/2018 01:11:55 PM <Removing container image greetings-python-2018-03-30-17-02-54. Reason: Removing app cont img greetings-python-2018-03-30-17-02-54>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:11:55 PM <Removing container image ubuntu. Reason: Removing app cont img ubuntu>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:11:55 PM <rmi command:docker rmi -f a35e70164dfb
>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:11:55 PM <Local deployer for called to delete service:mysql-greetings-python>: deploy_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/deployer/local_deployer.py:139
04/01/2018 01:11:55 PM <Stopping container mysql-greetings-python. Reason: Stopping service cont mysql-greetings-python>: stop_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:50
04/01/2018 01:11:56 PM <Removing container mysql-greetings-python. Reason: Removing service cont mysql-greetings-python>: remove_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:58
04/01/2018 01:11:56 PM <Removing container image mysql-greetings-python. Reason: Removing service cont img mysql-greetings-python>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:11:56 PM <Removing container image mysql. Reason: Removing app cont img mysql>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:11:56 PM <rmi command:docker rmi -f 0da48351c371
>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:12:17 PM <Executing GET for dep id:1>: get() cld.py:351
04/01/2018 01:12:20 PM <Executing GET for all apps>: get() cld.py:246
04/01/2018 01:12:28 PM <Executing DELETE for dep id:2>: delete() cld.py:327
04/01/2018 01:12:28 PM <App version:2018-03-30-17-05-42>: get_app_and_service_info() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/utils.py:315
04/01/2018 01:12:28 PM <App name:hello-world>: get_app_and_service_info() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/utils.py:315
04/01/2018 01:12:28 PM <Starting build/deploy for >: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
04/01/2018 01:12:28 PM <Manager -- delete>: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
04/01/2018 01:12:28 PM <Local generator called for delete for app:hello-world>: generate_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/generator/local_generator.py:96
04/01/2018 01:12:28 PM <Executing build step for delete>: build_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/builder.py:30
04/01/2018 01:12:28 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
04/01/2018 01:12:28 PM Found file at path: /Users/chow_vincent/.docker/config.json
04/01/2018 01:12:28 PM Found 'auths' section
04/01/2018 01:12:28 PM Auth data for {0} is absent. Client might be using a credentials store instead.
04/01/2018 01:12:28 PM Found 'credsStore' section
04/01/2018 01:12:28 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:12:28 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:12:28 PM <Local builder called for delete of app:hello-world>: build_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/local_builder.py:65
04/01/2018 01:12:28 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
04/01/2018 01:12:28 PM Found file at path: /Users/chow_vincent/.docker/config.json
04/01/2018 01:12:28 PM Found 'auths' section
04/01/2018 01:12:28 PM Auth data for {0} is absent. Client might be using a credentials store instead.
04/01/2018 01:12:28 PM Found 'credsStore' section
04/01/2018 01:12:28 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:12:28 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:12:28 PM <Local deployer for called to delete app:hello-world>: deploy_for_delete() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/deployer/local_deployer.py:139
04/01/2018 01:12:28 PM <Stopping container hello-world-2018-03-30-17-05-42. Reason: Stopping app cont hello-world-2018-03-30-17-05-42>: stop_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:50
04/01/2018 01:12:28 PM <stop command:docker stop 37886d818b97
>: stop_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:50
04/01/2018 01:12:28 PM <Removing container hello-world-2018-03-30-17-05-42. Reason: Removing app cont hello-world-2018-03-30-17-05-42>: remove_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:58
04/01/2018 01:12:28 PM <rm command:docker rm -f 37886d818b97
>: remove_container() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:58
04/01/2018 01:12:28 PM <Removing container image hello-world-2018-03-30-17-05-42. Reason: Removing app cont img hello-world-2018-03-30-17-05-42>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:12:28 PM <rmi command:docker rmi -f 5162f19ba800
>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:12:29 PM <Removing container image ubuntu. Reason: Removing app cont img ubuntu>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:12:29 PM <rmi command:docker rmi -f a35e70164dfb
>: remove_container_image() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:67
04/01/2018 01:12:34 PM <Executing GET for all apps>: get() cld.py:246
04/01/2018 01:13:07 PM <Received POST request.>: post() cld.py:490
04/01/2018 01:13:07 PM <Untarring received app tar file /Users/chow_vincent/.cld/data/deployments/greetings-python/2018-04-01-13-13-07/greetings-python.tar>: _untar_the_app() cld.py:414
04/01/2018 01:13:07 PM <Service id:1>: post() cld.py:490
04/01/2018 01:13:07 PM <App id:1>: post() cld.py:490
04/01/2018 01:13:07 PM <Location header:/deployments/1>: post() cld.py:490
04/01/2018 01:13:07 PM <Starting build/deploy for greetings-python>: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
04/01/2018 01:13:07 PM <Response:<Response 3 bytes [201 CREATED]>>: post() cld.py:490
04/01/2018 01:13:07 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
04/01/2018 01:13:07 PM Found file at path: /Users/chow_vincent/.docker/config.json
04/01/2018 01:13:07 PM Found 'auths' section
04/01/2018 01:13:07 PM Auth data for {0} is absent. Client might be using a credentials store instead.
04/01/2018 01:13:07 PM Found 'credsStore' section
04/01/2018 01:13:07 PM <Executing build step>: build() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/builder.py:19
04/01/2018 01:13:07 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
04/01/2018 01:13:07 PM Found file at path: /Users/chow_vincent/.docker/config.json
04/01/2018 01:13:07 PM Found 'auths' section
04/01/2018 01:13:07 PM Auth data for {0} is absent. Client might be using a credentials store instead.
04/01/2018 01:13:07 PM Found 'credsStore' section
04/01/2018 01:13:07 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:13:07 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:13:07 PM <Local builder called for service mysql-greetings-python>: build() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/builder/local_builder.py:106
04/01/2018 01:13:07 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
04/01/2018 01:13:07 PM Found file at path: /Users/chow_vincent/.docker/config.json
04/01/2018 01:13:07 PM Found 'auths' section
04/01/2018 01:13:07 PM Auth data for {0} is absent. Client might be using a credentials store instead.
04/01/2018 01:13:07 PM Found 'credsStore' section
04/01/2018 01:13:07 PM Trying paths: ['/Users/chow_vincent/.docker/config.json', '/Users/chow_vincent/.dockercfg']
04/01/2018 01:13:07 PM Found file at path: /Users/chow_vincent/.docker/config.json
04/01/2018 01:13:07 PM Found 'auths' section
04/01/2018 01:13:07 PM Auth data for {0} is absent. Client might be using a credentials store instead.
04/01/2018 01:13:07 PM Found 'credsStore' section
04/01/2018 01:13:07 PM <Sed pattern 1:RUN sed -i 's/\"access_token\".*/\"access_token\"/' credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:13:07 PM <Sed pattern 2:RUN sed -i "s/\"access_token\".*/\"access_token\":\"$token\",/" credentials 
>: _google_df_snippet() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/common/docker_lib.py:18
04/01/2018 01:13:07 PM <Local deployer called for service mysql>: deploy() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/deployer/local_deployer.py:181
04/01/2018 01:13:07 PM Deploying mysql container
04/01/2018 01:13:07 PM Environment string -e "MYSQL_ROOT_PASSWORD=testpass123!#$" 
04/01/2018 01:13:07 PM Environment string -e "MYSQL_ROOT_PASSWORD=testpass123!#$" -e "MYSQL_PASSWORD=testpass123!#$" 
04/01/2018 01:13:07 PM Environment string -e "MYSQL_ROOT_PASSWORD=testpass123!#$" -e "MYSQL_PASSWORD=testpass123!#$" -e "MYSQL_USER=testuser" 
04/01/2018 01:13:07 PM Environment string -e "MYSQL_ROOT_PASSWORD=testpass123!#$" -e "MYSQL_PASSWORD=testpass123!#$" -e "MYSQL_USER=testuser" -e "MYSQL_DATABASE=testdb" 
04/01/2018 01:13:07 PM Docker run cmd:docker run -e "MYSQL_ROOT_PASSWORD=testpass123!#$" -e "MYSQL_PASSWORD=testpass123!#$" -e "MYSQL_USER=testuser" -e "MYSQL_DATABASE=testdb"  -i -d --publish-all=true mysql:5.5
04/01/2018 01:13:10 PM <[Errno 2] No such file or directory: '/Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/service_handler/mysql/docker_host.txt'>: run() /Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/manager.py:35
04/01/2018 01:13:10 PM <[Errno 2] No such file or directory: '/Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/service_handler/mysql/docker_host.txt'>: start_thread() cld.py:44
04/01/2018 01:13:31 PM <Executing GET for all apps>: get() cld.py:246

(firstmile) Vincents-MacBook-Pro:firstmile chow_vincent$ cld app show
Please enter deploy id>1
+------------------+---------------------+--------------+------------------+----------+
|     App Name     |     App Version     |    Cloud     |      Status      | App Info |
+------------------+---------------------+--------------+------------------+----------+
| greetings-python | 2018-04-01-13-13-07 | local-docker | DEPLOYMENT_ERROR |          |
+------------------+---------------------+--------------+------------------+----------+

(firstmile) Vincents-MacBook-Pro:firstmile chow_vincent$ cld service show
Please enter service deploy id>1
+-----------+---------------------+--------------+----------------------------+--------------+
| Deploy ID |   Service Version   |    Cloud     |           Status           | Service Info |
+-----------+---------------------+--------------+----------------------------+--------------+
|     1     | 2018-04-01-13-13-07 | local-docker | DEPLOYING_SERVICE_INSTANCE |              |
+-----------+---------------------+--------------+----------------------------+--------------+

**Comment by devdattakulkarni** [comment]
@chowyvincent Thanks!

**Comment by devdattakulkarni** [comment]
@chowyvincent 

The error seems to be docker_host.txt file is not being found.

04/01/2018 01:13:10 PM <[Errno 2] No such file or directory: '/Users/chow_vincent/Documents/2018Spring/cs378/assignment4/firstmile/manager/service_handler/mysql/docker_host.txt'>: run() 

Can you search for docker_host.txt in your assignment4 folder and tell me its location?

**Comment by chowyvincent** [comment]
It's in /firstmile/client/cldcmds

**Comment by devdattakulkarni** [comment]
Thanks!

I will now push a fix to resolve this issue.

Will let you know when done.

**Comment by devdattakulkarni** [comment]
@chowyvincent 

I have pushed a fix.

Can you pull master and try one more time?

I can reopen the issue if required.

**Comment by devdattakulkarni** [comment]
Please add a comment if things worked or not.
